src/main/java/br/com/cactus/flatsystem/beans/ConfiguracaoBean.java
package br.com.cactus.flatsystem.beans;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ApplicationScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import br.com.cactus.flatsystem.entities.Configuracao;
import br.com.cactus.flatsystem.entities.Estabelecimento;
import br.com.cactus.flatsystem.service.ConfiguracaoService;
import br.com.cactus.flatsystem.service.EstabelecimentoService;


@ApplicationScoped
public class ConfiguracaoBean {
	
	private static final String PAG = "/pages/admin/configuracaoDoSistema?faces-redirect=true";
	private static final String PAG_CANCEL = "/pages/user/successfulPage?faces-redirect=true";
	
	private Estabelecimento estabelecimento;
	private Configuracao config;
	
	@Inject
	private EstabelecimentoService estabelecimentoService;
	@Inject
	private ConfiguracaoService configService;
	
	@PostConstruct
	public String novo(){
		if (estabelecimentoService.lista().isEmpty()){
			estabelecimento = new Estabelecimento();
		}else {
			estabelecimento = estabelecimentoService.lista().get(0);
		}
		
		if (configService.lista().isEmpty()){
			config = new Configuracao();
		}else {
			config = configService.lista().get(0);
		}
		
		return null;
	}
	
	public String salvarEstabelecimento(){
		if (estabelecimentoService.lista().isEmpty()){
			estabelecimentoService.salvar(estabelecimento);
			FacesMessage msg = new FacesMessage("Sucesso!", "Estabelecimento Salvo!");  
		    FacesContext.getCurrentInstance().addMessage(null, msg);  
		}else {
			estabelecimentoService.update(estabelecimento);
			FacesMessage msg = new FacesMessage("Sucesso!", "Estabelecimento Editado! ");  
		    FacesContext.getCurrentInstance().addMessage(null, msg);  
		}
		
		return PAG;
	}
	
	public String salvarConfig(){
		if (configService.lista().isEmpty()){
			configService.salvar(config);
			 FacesMessage msg = new FacesMessage("Sucesso!", "Configuração Salva!");  
		     FacesContext.getCurrentInstance().addMessage(null, msg);  
		}else{
			configService.update(config);
			FacesMessage msg = new FacesMessage("Sucesso!", "Configuração Editada!");    
		    FacesContext.getCurrentInstance().addMessage(null, msg);  
		}
		
		return PAG;
	}

	public String cancelar(){
		return PAG_CANCEL;
	}

	public Estabelecimento getEstabelecimento() {
		return estabelecimento;
	}

	public void setEstabelecimento(Estabelecimento estabelecimento) {
		this.estabelecimento = estabelecimento;
	}

	public Configuracao getConfig() {
		return config;
	}

	public void setConfig(Configuracao config) {
		this.config = config;
	}
	
	public String pagConfiguracao(){
		return PAG;
	}
	
}

src/main/java/br/com/cactus/flatsystem/beans/RoleBean.java
package br.com.cactus.flatsystem.beans;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;


import br.com.cactus.flatsystem.entities.Role;
import br.com.cactus.flatsystem.service.RoleService;



@ViewScoped
public class RoleBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Role role = new Role();
	private List<Role> lista;
	
	@Inject
	private RoleService roleService;
	
	public String novo(){
		role = new Role();
		
		return "#";//"/pages/user/cadastroApartamentos";
	}
	
	public String salvar(){
		this.novo();
		this.lista = null;
		return "#";//"/pages/user/cadastroApartamentos";
	}
	
	public String cancelar(){
		this.lista = null;
		return "#";//"/pages/user/cadastroApartamentos";	
	}
	
	public String editar(){
		return "#";//"/pages/user/cadastroApartamentos";
	}
	
	public String update(){
		roleService.update(role);
		this.lista = null;
		return "#";//"/pages/user/cadastroApartamentos";
	}
	
	public String remover(){		
		roleService.remover(role);
		this.novo();
		this.lista = null;
		return "#";//"/pages/user/cadastroApartamentos";
	}
	
	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public List<Role> getLista() {
		if (this.lista == null){
			lista = roleService.lista();
		}
		return lista;
	}

	public void setLista(List<Role> lista) {
		this.lista = lista;
	}
	
	public List<SelectItem> getPermissoes() {
		List<SelectItem> lst = new ArrayList<SelectItem>();
		for (int i = 0; i < getLista().size(); i++){
			lst.add(new SelectItem('S', "Sim"));
		}
		return lst;
	}
	
	
	
}

src/main/java/br/com/cactus/flatsystem/entities/Configuracao.java
package br.com.cactus.flatsystem.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
@SequenceGenerator(name="config_codigo_seq", sequenceName="config_codigo_seq", allocationSize=1)
public class Configuracao implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4660735641327824338L;

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="config_codigo_seq")
	@Column(name="configuracao_id")
	private long id;
	
	@Temporal(TemporalType.TIME)
	private Date horaInicioHospedagem;

	@Temporal(TemporalType.TIME)
	private Date toleranciaHospedagem;
	
	private boolean calculaMeiaHospedagem;
	
	@OneToMany
	private List<WebService> webServices;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Date getHoraInicioHospedagem() {
		return horaInicioHospedagem;
	}

	public void setHoraInicioHospedagem(Date horaInicioHospedagem) {
		this.horaInicioHospedagem = horaInicioHospedagem;
	}
	
	public Date getToleranciaHospedagem() {
		return toleranciaHospedagem;
	}

	public void setToleranciaHospedagem(Date toleranciaHospedagem) {
		this.toleranciaHospedagem = toleranciaHospedagem;
	}
	
	public boolean isCalculaMeiaHospedagem() {
		return calculaMeiaHospedagem;
	}

	public void setCalculaMeiaHospedagem(boolean calculaMeiaHospedagem) {
		this.calculaMeiaHospedagem = calculaMeiaHospedagem;
	}

	public List<WebService> getWebServices() {
		return webServices;
	}

	public void setWebServices(List<WebService> webServices) {
		this.webServices = webServices;
	}


	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (calculaMeiaHospedagem ? 1231 : 1237);
		result = prime
				* result
				+ ((horaInicioHospedagem == null) ? 0 : horaInicioHospedagem
						.hashCode());
		result = prime * result + (int) (id ^ (id >>> 32));
		result = prime
				* result
				+ ((toleranciaHospedagem == null) ? 0 : toleranciaHospedagem
						.hashCode());
		result = prime * result
				+ ((webServices == null) ? 0 : webServices.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Configuracao other = (Configuracao) obj;
		if (calculaMeiaHospedagem != other.calculaMeiaHospedagem)
			return false;
		if (horaInicioHospedagem == null) {
			if (other.horaInicioHospedagem != null)
				return false;
		} else if (!horaInicioHospedagem.equals(other.horaInicioHospedagem))
			return false;
		if (id != other.id)
			return false;
		if (toleranciaHospedagem == null) {
			if (other.toleranciaHospedagem != null)
				return false;
		} else if (!toleranciaHospedagem.equals(other.toleranciaHospedagem))
			return false;
		if (webServices == null) {
			if (other.webServices != null)
				return false;
		} else if (!webServices.equals(other.webServices))
			return false;
		return true;
	}
		
}

src/main/webapp/pages/admin/adminPage.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">

<h:head>
	<title>Admin Page - Spring Security</title>
</h:head>
<h:body>
	<h:form>
		<h:messages />
		<h:outputText value="Você possui a permissão ROLE_ADMIN!" />
	</h:form>
</h:body>
</html>

src/main/webapp/pages/admin/cadastroUsuarios.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Controle de Pousada</title>
</h:head>
<h:body>
	<ui:decorate template="/pages/padrao.xhtml">
	
		<ui:define name="centro"> 	
    	<h:form id="cadastro_usuarios" acceptcharset="ISO-8859-1">  
    		<p:focus context="cadastro_usuarios"/> 
    		<p:messages id="messagensErro" showSummary="false" showDetail="true" autoUpdate="true" closable="true" />    	 	
    		<p:panel header="Cadastro de Usuários">   
	        	<h:panelGrid columns="2">   
	    			<p:outputLabel for="nome_usuario" value="Nome: "/>
	    			<p:inputText id="nome_usuario" value="#{userBean.user.username}" required="true"/>
	    			
	    			<p:outputLabel for="senha" value="Senha: "/>
	    			<p:inputText type="password" id="senha" value="#{userBean.user.password}"
	    				required="true" requiredMessage="Atenção! Campo Senha Obrigatório"/>
	    			
	    			<p:outputLabel for="confirmacao" value="Confirmação: "/>
	    			<p:inputText type="password" id="confirmacao" value="#{userBean.confirmacaoSenha}"
	    				required="true" requiredMessage="Atenção! Campo Confirma Senha Obrigatório!">
	    				<p:ajax event="blur" update=":cadastro_usuarios:messagensErro" listener="#{userBean.verificaSenha}"/>
	    			</p:inputText>
	    			
	    			<p:outputLabel for="permissao" value="Tipo de Usuario: "/>
	    			<p:selectOneMenu id="permissao" value="#{userBean.roleSelecionada}" style="width: 158px" >
			            <f:selectItems value="#{userBean.permissoes}" />    
			        </p:selectOneMenu>		
	    					        	
	        	</h:panelGrid> 
	        	<f:facet name="footer">
		        		<p:toolbar id="tb"> 
			        		<p:toolbarGroup align="center"> 	
			        			<center>		        		
					     			<p:commandButton value="Salvar" ajax="false" action="#{userBean.salvar}" update="cadastro_usuario" icon="ui-icon-disk"/>
					     			<p:separator /> 
					     			<p:commandButton value="Cancelar" immediate="true" ajax="false" action="#{userBean.cancelar}" update="cadastro_usuario" icon="ui-icon-trash"/>
				     			</center>
			     			</p:toolbarGroup> 
		     			</p:toolbar>
		     			<p:sticky target="tb" />  
	        		</f:facet>         		
			</p:panel>
    	</h:form>
    </ui:define>
    </ui:decorate>
</h:body>
</html>

src/main/webapp/pages/admin/configuracao.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<h:head>
	<title>Configuração</title>
</h:head>
<h:body>

	<ui:decorate template="/pages/padrao.xhtml">
		<ui:define name="centro">
			<h:form>
				<p:messages id="messages" showDetail="true" autoUpdate="true"
					closable="true" />
			</h:form>
		</ui:define>

	</ui:decorate>
	<p:layout fullPage="true">
		<p:layoutUnit position="center">
			<ui:insert name="centro_conf">
	                   O que estiver aqui será substituido!
	        </ui:insert>
		</p:layoutUnit>
	</p:layout>
</h:body>
</html>

src/main/webapp/pages/admin/configuracaoDoSistema.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:sec="http://www.springframework.org/security/facelets/tags"
      xmlns:stella="http://stella.caelum.com.br/faces2">

    <h:head>
        <title>Configurações</title>
    </h:head>
    <h:body>
        <ui:decorate template="/pages/padrao.xhtml">
            <ui:define name="centro">
                <h:form id="geral">
                    <p:panel header="Configurações Globais">
                        <p:growl id="growl" showDetail="true" sticky="false" life="3000"/>
                        <p:tabView id="tabView">

                            <p:tab id="tabela1" title="Empresa">

                                <h:panelGrid columns="4" cellpadding="5">
                                    <p:outputLabel value="Razão Social" />
                                    <p:inputText id="rs"
                                                 value="#{configuracaoBean.estabelecimento.razaoSocial}" />
                                    <p:outputLabel value="Nome Fantasia" />
                                    <p:inputText id="nm"
                                                 value="#{configuracaoBean.estabelecimento.fantasia}" />
                                    <p:outputLabel value="CNPJ" />
                                    <p:inputMask id="cnpj"
                                                 value="#{configuracaoBean.estabelecimento.cnpj}"
                                                 mask="99.999.999/9999-99">
                                        <stella:validateCNPJ formatted="true" />
                                    </p:inputMask>
                                    <p:outputLabel value="Inscrição Estadual" />
                                    <p:inputText id="ie"
                                                 value="#{configuracaoBean.estabelecimento.ie}" />
                                    <p:outputLabel value="Inscrição Municipal" />
                                    <p:inputText id="im"
                                                 value="#{configuracaoBean.estabelecimento.im}" />
                                    <p:outputLabel value="Telefone" />
                                    <p:inputMask id="tel"
                                                 value="#{configuracaoBean.estabelecimento.telefone}"
                                                 mask="(99) 9999-9999" />
                                    <p:outputLabel value="Fax" />
                                    <p:inputMask id="fax"
                                                 value="#{configuracaoBean.estabelecimento.fax}"
                                                 mask="(99) 9999-9999" />
                                    <p:outputLabel value="Email" />
                                    <p:inputText id="email"
                                                 value="#{configuracaoBean.estabelecimento.email}" />
                                </h:panelGrid>
                                <p:accordionPanel>
                                    <p:tab title="Endereço">
                                        <h:panelGrid columns="4" cellpadding="10">
                                            <p:outputLabel value="Rua: " />
                                            <p:inputText id="rua"
                                                         value="#{configuracaoBean.estabelecimento.endereco.rua}" />
                                            <p:outputLabel value="Número: " />
                                            <p:inputText id="numero"
                                                         value="#{configuracaoBean.estabelecimento.endereco.numero}" />
                                            <p:outputLabel value="Bairro: " />
                                            <p:inputText
                                                value="#{configuracaoBean.estabelecimento.endereco.bairro}" />
                                            <p:outputLabel value="Complemento: " />
                                            <p:inputText
                                                value="#{configuracaoBean.estabelecimento.endereco.complemento}" />
                                            <p:outputLabel value="CEP: " />
                                            <p:inputMask
                                                value="#{configuracaoBean.estabelecimento.endereco.cep}"
                                                mask="99999-999" />
                                            <p:outputLabel value="Cidade: " />
                                            <p:inputText id="cidade"
                                                         value="#{configuracaoBean.estabelecimento.endereco.cidade}" />
                                            <p:outputLabel value="UF: " />
                                            <p:inputText
                                                value="#{configuracaoBean.estabelecimento.endereco.uf}"
                                                size="2" maxlength="2" />
                                        </h:panelGrid>
                                        <p />
                                    </p:tab>
                                </p:accordionPanel>
                                <h:panelGrid columns="2" cellpadding="5">
                                    <p:commandButton value="Salvar" icon="ui-icon-disk"
                                                     actionListener="#{configuracaoBean.salvarEstabelecimento}" update=":geral:growl">

                                    </p:commandButton>
                                    <p:commandButton value="Cancelar" icon=" ui-icon-closethick"
                                                     action="#{configuracaoBean.cancelar}">

                                    </p:commandButton>
                                </h:panelGrid>
                            </p:tab>

                            <p:tab id="tabela2" title="Sistema">
                                <h:panelGrid columns="2" cellpadding="5">
                                    <p:outputLabel value="Horário inicio hospedagem" />
                                    <p:calendar
                                        value="#{configuracaoBean.config.horaInicioHospedagem}"
                                        pattern="HH:mm" timeOnly="true" showOn="button" />
                                    <p:outputLabel value="Tolerância hospedagem: " />
                                    <p:calendar id="tl"
                                                value="#{configuracaoBean.config.toleranciaHospedagem}"
                                                pattern="HH:mm" timeOnly="true" showOn="button" />
                                    <h:outputText value="Calcula Meia Hospedagem: " />
                                    <p:selectBooleanButton
                                        value="#{configuracaoBean.config.calculaMeiaHospedagem}"
                                        onLabel="Sim" offLabel="Não" />
                                </h:panelGrid>
                                <div style="margin-top: 30px;">
                                    <center>
                                        <p:commandButton value="Salvar" icon="ui-icon-disk"
                                                         actionListener="#{configuracaoBean.salvarConfig}" update=":geral:growl">

                                        </p:commandButton>

                                        <p:commandButton value="Cancelar" icon=" ui-icon-closethick"
                                                         action="#{configuracaoBean.cancelar}">

                                        </p:commandButton>
                                    </center>
                                </div>
                            </p:tab>
                        </p:tabView>
                    </p:panel>
                </h:form>
            </ui:define>
        </ui:decorate>
    </h:body>
</html>

src/main/webapp/pages/admin/configuracaoGlobal.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sec="http://www.springframework.org/security/facelets/tags"
	xmlns:stella="http://stella.caelum.com.br/faces2">

<h:head>
	<title>Configurações Gobais</title>
</h:head>
<h:body>
	<ui:decorate template="/pages/padrao.xhtml">
		<ui:define name="centro">
			<h:form>
				<p:messages id="messages" showDetail="true" autoUpdate="true"
					closable="true" />

				<p:panel header="Configurações Globais" >
					<h:panelGrid columns="2">
						<p:outputLabel for="razao" value="Razão Social: " />
						<p:inputText id="razao"
							value="#{fornecedorBean.fornecedor.razaoSocial}" />
						<p:outputLabel for="fantasia" value="Fantasia: " />
						<p:inputText id="fantasia"
							value="#{fornecedorBean.fornecedor.fantasia}" />
						<p:outputLabel for="cnpj" value="CNPJ: " />
						<p:inputMask id="cnpj" value="#{fornecedorBean.fornecedor.cnpj}"
							mask="99.999.999/9999-99">
							<stella:validateCNPJ formatted="true" />
						</p:inputMask>
						<p:outputLabel for="inscricao" value="Escrição Estadual: " />
						<p:inputMask id="inscricao"
							value="#{fornecedorBean.fornecedor.inscricaoEstadual}"
							mask="99.999999-9" />
						<p:outputLabel for="telefone" value="Telefone: " />
						<p:inputMask id="telefone"
							value="#{fornecedorBean.fornecedor.telefone}"
							mask="(99) 9999-9999" />
						<p:outputLabel for="email" value="E-mail: " />
						<p:inputText id="email"
							value="#{fornecedorBean.fornecedor.email}" />
					</h:panelGrid>
				</p:panel>
			</h:form>
		</ui:define>
	</ui:decorate>
</h:body>
</html>

src/main/webapp/pages/admin/listaUsuarios.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" 
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:sec="http://www.springframework.org/security/facelets/tags" >

<h:head>
	<title>Controle de Pousada</title>
	<h:outputStylesheet library="css" name="estilo.css"/>
</h:head>
<h:body>
	<ui:decorate template="/pages/padrao.xhtml">
	
		<ui:define name="centro"> 	
    	 	
    		<p:panel header="Usuários Cadastrados" >
			<h:form id="listaUsuarios" acceptcharset="ISO-8859-1">
				<p:toolbar id="tb">
					<p:toolbarGroup align="left"> 
						<p:commandButton value="Novo Usuario" action="#{userBean.novo}" ajax="false" icon="ui-icon-plus"/>
						<p:separator /> 
					</p:toolbarGroup>
				</p:toolbar>  
				<p:sticky target="tb" /> <p/>
	        	<p:dataTable value="#{userBean.lista}" var="user" widgetVar="widg"
	        	 paginator="true" rows="10" rowIndexVar="rowIx" rowStyleClass="#{rowIx mod 2 eq 0 ? 'even-row' : 'odd-row'}" 
                 paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"  
                 rowsPerPageTemplate="5,10,15"> 
                 	
                 	<p:column headerText="Código">
			        <center>
			        	<h:outputText value="#{user.id}" />
			        </center>	
		        	</p:column> 
	        		<p:column headerText="Usuário">
	        		<center>
	        			<h:outputText value="#{user.username}" />
	        		</center>	
	        		</p:column>	    

	        		<!-- <p:column headerText="Capacidade">
	        		<center>
	        			<h:outputText value="#{apartamento.capacidade}"/>
	        		</center>	
	        		</p:column>    	
	        		<p:column headerText="Valor Diária">
	        		<center>
	        			<h:outputText value="#{apartamento.valor_diaria}"/>
	        		</center>	
	        		</p:column>  
	        		<p:column headerText="Descrição">
	        		<center>
	        			<h:outputText value="#{apartamento.descricao}"/>
	        		</center>	
	        		</p:column>  -->
	        		<p:column headerText="Opções">
	        		<center>
	        			<sec:ifAnyGranted roles="ROLE_ADMIN">
						<p:commandButton action="#{userBean.editar}" icon="ui-icon-pencil" title="Editar">
							<f:setPropertyActionListener target="#{userBean.user}"
								value="#{user}" />
							<f:setPropertyActionListener
								target="#{userBean.user}" value="#{user}" />
							</p:commandButton>
						</sec:ifAnyGranted>
		        			
	        			<sec:ifAnyGranted roles="ROLE_ADMIN">
						<p:commandButton action="#{userBean.remover}"
							onclick="if (!confirm('Confirma a exclusão do Usuário #{user.username}?')) return false;"
							title="Excluir Usuário" icon="ui-icon-trash">
							<f:setPropertyActionListener target="#{userBean.user}"
								value="#{user}" />
						</p:commandButton>
					</sec:ifAnyGranted>
	        		</center>	
	        		</p:column>
	        		
	        	</p:dataTable> 
	        	
	        </h:form>       		
			</p:panel>
    
      </ui:define>
  </ui:decorate>
</h:body>
</html>